---
title: "Introduction to Time Series Analysis"
author: "Basem Aljoumani"
date: "23 4 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(astsa)
library(xts)
```



```{r}
help(AirPassengers)

```

```{r}
plot(AirPassengers)
```

```{r}
#Plot the DJIA daily closings
plot(djia$Close)
```

```{r}
#Plot the Southern Oscillation Index
plot(soi)
```


```{r}
# Plot globtemp and detrended globtemp
data("globtemp")
par(mfrow = c(2,1))
plot(globtemp) 
plot(diff(globtemp))

# Plot cmort and detrended cmort
par(mfrow = c(2,1))
plot(cmort)
plot(diff(cmort))

```


```{r}
# trend and heteroscedasticity
# astsa and xts are preloaded 

# Plot GNP series (gnp) and its growth rate
par(mfrow = c(2,1))
plot(gnp)
plot(diff(log(gnp)))

# Plot the DJIA closings (djia$Close) and its returns
par(mfrow = c(2,1))
plot(djia$Close)
plot(diff(log((djia$Close))))

```


******

```{r}
# Generate and plot white noise
WN <- arima.sim(model = list(order = c(0, 0, 0)), n = 200)
plot(WN)

# Generate and plot an MA(1) with parameter .9 by filtering the noise
MA <- arima.sim(model = list(order = c(0, 0, 1), ma = .9), n = 200)  
plot(MA)

# Generate and plot an AR(1) with parameters 1.5 and -.75
AR <- arima.sim(model = list(order = c(2, 0, 0), ar = c(1.5, -.75)), n = 200) 
plot(AR)

```

****
9 -15
***

```{r}

x <- arima.sim(model =list(order=c(1,0,0),ar =-0.7), n =200)
y <- arima.sim(model =list(order=c(0,0,1), ma=-0.7), n =200)
par(mfrow =c(1,2))
plot(x, main ="AR(1)")
plot(y, main ="MA(1)")
```





```{r}
# Generate 100 observations from the AR(1) model
x <- arima.sim(model = list(order = c(1, 0, 0), ar = .9), n = 100)

# Plot the generated data  
plot(x)

# Plot the sample P/ACF pair
acf2(x)

# Fit an AR(1) to the data and examine the t-table
sarima(x, p = 1, d = 0, q = 0)

```


***
16-19
***

```{r}
#Fitting an ARMA model,

x <- arima.sim(model = list(order = c(2, 0, 1), ar = c(1, -.9), ma = .8), n = 250)

```


```{r}
plot(x) 
```
```{r}
#Plot the sample P/ACF of x
acf2(x)
```

```{r}
#Fit an ARMA(2,1) to the data and examine the t-table
x_fit <- sarima(x, p = 2, d = 0, q = 1)
x_fit$ttable
```


***
20 -21
**

```{r}
gnpgr <-diff(log(gnp))

acf2(gnpgr)
sarima(gnpgr, p=1, d= 0, q= 0)
```

```{r}
sarima(gnpgr, p=1, d= 0, q= 2)
```

```{r}
data("varve")
plot(varve)

dl_varve <- diff(log(varve))

```

```{r}
acf2(dl_varve)
# Fit an MA(1) to dl_varve.   
sarima(dl_varve, p = 0, d = 0, q = 1)

# Fit an MA(2) to dl_varve. Improvement?
sarima(dl_varve, p = 0, d = 0, q = 2)

# Fit an ARMA(1,1) to dl_varve. Improvement?
sarima(dl_varve, p = 1, d = 0, q = 1)

```
```{r}
# Fit an MA(1) to dl_varve. Examine the residuals  
sarima(dl_varve, p = 0, d = 0, q = 1)

# Fit an ARMA(1,1) to dl_varve. Examine the residuals
sarima(dl_varve, p = 1, d = 0, q = 1)

```
#ARMA 
```{r}
data("oil")
plot(oil)

# Calculate approximate oil returns
oil_returns <- diff(log(oil))

# Plot oil_returns. Notice the outliers.
plot(oil_returns)

# Plot the P/ACF pair for oil_returns
acf2(oil_returns)

# Assuming both P/ACF are tailing, fit a model
sarima(oil_returns, p = 1, d = 0, q = 1)

```


***
22-23
**

```{r}
x <- arima.sim(list(order=c(1,1,0), ar =0.9), n = 200)

par(mfrow=c(1,2))
plot(x, main= "ARIMA(p=1, d=1, q=0)")
plot(diff(x), main="ARMA(p=1,d=0,q=0)")

```

```{r}
#plot the data
x <- arima.sim(model = list(order = c(1, 1, 0), ar = .9), n = 200)
```

```{r}
# Plot the P/ACF pair of x
acf2(x)

```

```{r}
# Plot the differenced data
plot(diff(x))

```

```{r}
# Plot the P/ACF pair of the differenced data
acf2(diff(x))
```
#Simulated ARIMA
```{r}

# Plot sample P/ACF of differenced data and determine model
acf2(diff(x))
```

```{r}
# Estimate parameters and examine output
sarima(x, p = 2, d = 1, q = 0)

```


#annual global temperature deviations to 2015
```{r}
data("globtemp")
plot(globtemp)

```

```{r}
# Plot the sample P/ACF pair of the differenced data 
acf2(diff(globtemp))

# Fit an ARIMA(1,1,1) model to globtemp
sarima(globtemp, p = 1, d = 1, q = 1)

# Fit an ARIMA(0,1,2) model to globtemp. Which model is better?
sarima(globtemp, p = 0, d = 1, q = 2)
```
***
24 -25
***

```{r}
#Weekly oil Prices ARIMA (1,1,1)
oil <- window (oil , end = 2006)
plot(oil)
acf2(diff(oil))
x <- sarima(oil , p = 1, d= 1, q= 1)
x$ttable

```
```{r}
oil <- window (oil , end = 2006)

x2 <- sarima(oil , p = 2, d= 1, q= 1)
x2$ttable
```

#Diagnostics - global temperatures , we already fit an ARIMA(1,1,1) and an ARIMA(0,1,2).
#check the residual diagnostics and use AIC and BIC for model choice.
```{r}
# Fit ARIMA(0,1,2) to globtemp and check diagnostics  
sarima(globtemp, p = 0, d = 1, q = 2)

# Fit ARIMA(1,1,1) to globtemp and check diagnostics
sarima(globtemp, p = 1, d = 1, q = 1)

# Which is the better model?
"ARIMA(0,1,2)"
#try fitting an ARIMA(1,1,2) or an ARIMA(0,1,3) to the data. 
```

***
26 29
***
#Forecasting simulated ARIMA
```{r}

oil <- window(astsa::oil, end =2006)
oilf <- window(astsa::oil, end =2007)

sarima.for(oil, n.ahead=52,1,1,1)
lines(oilf)

```
#global temperatures, Forecast data 35 years into the future
```{r}
# Fit an ARIMA(0,1,2) to globtemp and check the fit
sarima(globtemp, p = 0, d = 1, q = 2)

# Forecast data 35 years into the future
sarima.for(globtemp, n.ahead = 35, p = 0, d = 1, q = 2) 

```

***
30-
***

#model to the monthly US unemployment data
```{r}
data("unemp")
# Plot unemp 
plot(unemp)

# Difference your data and plot
d_unemp <- diff(unemp)
plot(d_unemp)

# Plot seasonal differenced diff_unemp
dd_unemp <- diff(d_unemp, lag = 12)   
plot(dd_unemp)

```

```{r}
# Plot P/ACF pair of the fully differenced data to lag 60
dd_unemp <- diff(diff(unemp), lag = 12)
acf2(dd_unemp, max.lag = 60)

# Fit an appropriate model
sarima(unemp, p = 2, d = 1, q = 0, P = 0, D = 1, Q = 1, S = 12)
```

***
35
***





```{r}
# Fit your previous model to unemp and check the diagnostics
sarima(unemp, p = 2, d = 1, q = 0, P = 0, D = 1, Q = 1, S = 12)

# Forecast the data 3 years into the future
sarima.for(unemp, n.ahead = 36, p = 2, d = 1, q = 0, P = 0, D = 1, Q = 1, S = 12)

```

